BossMod/Modules/Endwalker/DeepDungeon/EurekaOrthos/DD90Administrator.cs
Orthos floor 90 boss module fully completed, here's a video of it if you'd like actual feedback material on what it looks like
https://youtu.be/3Vabhr27W60?si=UDZDPHaaRshkQoEi
=> Orthos Floor 90 Boss Complete

BossMod/Modules/Endwalker/DeepDungeon/EurekaOrthos/DD90Administrator.cs
=> Fixed Floor 90 Admin Bounds (sorry bout that)

BossMod/AI/AIManager.cs, BossMod/Config/ConfigRoot.cs, BossMod/Framework/Plugin.cs, BossMod/Modules/Endwalker/DeepDungeon/EurekaOrthos/DD30TiamatsClone.cs
Readd /vbm and /vbmai to support backwards compatibility and AutoDuty
=> Vbm command reimplement

BossMod/Modules/Stormblood/Trial/T05Yojimbo/T05Yojimbo.cs, BossMod/Modules/Stormblood/Trial/T07Byakko/T07Byakko.cs, BossMod/Modules/Stormblood/Trial/T07Byakko/T07ByakkoEnums.cs, BossMod/Modules/Stormblood/Trial/T07Byakko/T07ByakkoStates.cs, BossMod/Modules/Stormblood/Trial/T08Suzaku/T08Suzaku.cs, BossMod/Modules/Stormblood/Trial/T08Suzaku/T08SuzakuEnums.cs, BossMod/Modules/Stormblood/Trial/T08Suzaku/T08SuzakuStates.cs
no clue how were going to handle DDR in Hells Kier
=> The Jade Stoa and Hells Kier first passes

BossMod/Modules/Endwalker/Dungeon/D13LunarSubterrane/D131DarkElf.cs, BossMod/Modules/Endwalker/Dungeon/D13LunarSubterrane/D132DamcyanAntilon.cs, BossMod/Modules/Endwalker/Dungeon/D13LunarSubterrane/D133Durante.cs
knockback AI for 2nd bosses included
=> Lunar Subterrane modules verified

BossMod/Modules/Dawntrail/Dungeon/D01Ihuykatumu/D011PrimePunutiy.cs, BossMod/Modules/Dawntrail/Dungeon/D01Ihuykatumu/D012Drowsie.cs, BossMod/Modules/Dawntrail/Dungeon/D01Ihuykatumu/D013Apollyon.cs, BossMod/Modules/Dawntrail/Dungeon/D02WorqorZormor/D021Ryoqor.cs, BossMod/Modules/Dawntrail/Dungeon/D02WorqorZormor/D022Kahderyor.cs, BossMod/Modules/Dawntrail/Dungeon/D02WorqorZormor/D023Gurfurlur.cs, BossMod/Modules/Dawntrail/Dungeon/D03Skydeep/D031FeatherRay.cs, BossMod/Modules/Dawntrail/Dungeon/D03Skydeep/D032Firearms.cs, BossMod/Modules/Dawntrail/Dungeon/D03Skydeep/D033Maulskull.cs, BossMod/Modules/Dawntrail/Dungeon/D04Vanguard/D041CommanderR8.cs, BossMod/Modules/Dawntrail/Dungeon/D04Vanguard/D042Protector.cs, BossMod/Modules/Dawntrail/Dungeon/D04Vanguard/D043Zander.cs, BossMod/Modules/Dawntrail/Dungeon/D05Origenics/D051Herpekaris.cs, BossMod/Modules/Dawntrail/Dungeon/D05Origenics/D052Deceiver.cs, BossMod/Modules/Dawntrail/Dungeon/D05Origenics/D053Ambrose.cs, BossMod/Modules/Dawntrail/Dungeon/D06Alexandria/D061AntivirusX.cs, BossMod/Modules/Dawntrail/Dungeon/D06Alexandria/D062Amalgam.cs, BossMod/Modules/Dawntrail/Dungeon/D06Alexandria/D063Eliminator.cs, BossMod/Modules/Dawntrail/Dungeon/D07TenderValley/D071Barreltender.cs, BossMod/Modules/Dawntrail/Dungeon/D07TenderValley/D072Anthracite.cs, BossMod/Modules/Dawntrail/Dungeon/D07TenderValley/D073Serpent.cs, BossMod/Modules/Dawntrail/Dungeon/D08Deadwalk/D081Leonogg.cs, BossMod/Modules/Dawntrail/Dungeon/D08Deadwalk/D082Jack.cs, BossMod/Modules/Dawntrail/Dungeon/D08Deadwalk/D083Traumerei.cs, BossMod/Modules/Shadowbringers/Alliance/A12Hobbes/A12HobbesEnums.cs
All modules listed as WIP, regardless of status. Some bosses are entirely complete, some need just arena adjustments, few missing a mechanic or two.
=> Initial support pass for every Dawntrail dungeon

BossMod/Modules/Dawntrail/Dungeon/D06Alexandria/D061AntivirusX.cs
Please.. squash this PR.. just for all of us.
=> Style fix for Alexandria B1

BossMod/Modules/Dawntrail/Raid/M1NBIackCat/M1NBIackCat.cs, BossMod/Modules/Dawntrail/Raid/M1NBIackCat/M1NBIackCatEnums.cs, BossMod/Modules/Dawntrail/Raid/M1NBIackCat/M1NBIackCatStates.cs, BossMod/Modules/Dawntrail/Raid/M2NHoneyB/M2NHoneyB.cs, BossMod/Modules/Dawntrail/Raid/M2NHoneyB/M2NHoneyBEnums.cs, BossMod/Modules/Dawntrail/Raid/M2NHoneyB/M2NHoneyBStates.cs, BossMod/Modules/Dawntrail/Raid/M3NBruteBomber/M3NBruteBomber.cs, BossMod/Modules/Dawntrail/Raid/M3NBruteBomber/M3NBruteBomberEnums.cs, BossMod/Modules/Dawntrail/Raid/M3NBruteBomber/M3NBruteBomberStates.cs, BossMod/Modules/Dawntrail/Raid/M4NWickedThunder/M4NWickedThunder.cs, BossMod/Modules/Dawntrail/Raid/M4NWickedThunder/M4NWickedThunderEnums.cs, BossMod/Modules/Dawntrail/Raid/M4NWickedThunder/M4NWickedThunderStates.cs
surprisingly complete, arena sizes not verified
=> M1N, M2N, M3N, and M4N WIP support

BossMod/Modules/Stormblood/Dungeon/D01SirensongSea/D011Lugat.cs, BossMod/Modules/Stormblood/Dungeon/D01SirensongSea/D012TheGovernor.cs, BossMod/Modules/Stormblood/Dungeon/D01SirensongSea/D013Lorelei.cs
There are supposedly some style issues.. but I can't find them.
What it tells me seems.. wildly inconsistent.
=> Sirensong B1-3

BossMod/Modules/Dawntrail/Hunt/RankA/Keheniheyamewi.cs
Follow-up to #320 
From all the modules added, was the only issue I encountered during trains so far.
Seems these changes resolve it after a bit of testing.
=> Keheniheyamewi Module Updates

BossMod/Modules/Dawntrail/Hunt/RankA/CatsEye.cs, BossMod/Modules/Dawntrail/Hunt/RankA/Keheniheyamewi.cs, BossMod/Modules/Dawntrail/Hunt/RankA/Nechuciho.cs, BossMod/Modules/Dawntrail/Hunt/RankA/Pkuucha.cs, BossMod/Modules/Dawntrail/Hunt/RankA/QueenHawk.cs, BossMod/Modules/Dawntrail/Hunt/RankA/RraxYitya.cs, BossMod/Modules/Dawntrail/Hunt/RankA/SallyTheSweeper.cs, BossMod/Modules/Dawntrail/Hunt/RankA/Starcrier.cs, BossMod/Modules/Dawntrail/Hunt/RankA/TheRaintriller.cs, BossMod/Modules/Dawntrail/Hunt/RankA/Yehehetoauapyo.cs
- Nechuciho 7.1 Rewrite
- Forced March clarity improvements in Kehe and Queen Hawk modules.
- Maturity bump on all modules towards Verified.
Please let me know if you would like me to revert the maturity changes. As it's been a while and I'm not aware of many complaints, I thought it would be appropriate to have them on by default.
=> DT A Ranks 7.1

BossMod/Modules/Dawntrail/Hunt/RankA/Keheniheyamewi.cs, BossMod/Modules/Dawntrail/Hunt/RankA/Pkuucha.cs
Addresses possible improvements relayed on the Discord
Pkuucha:
- Rewrite and simplification.
- Telegraph mechanics far earlier for AI to have plenty of time to move.
Keheniheyamewi:
- Fixes issue where AOEs were removed too early, resulting in AI movement error.
Changes quickly tested in-game 1v1 against the mobs, seemed to pass.
=> DT A Rank AI Improvements

BossMod/Modules/RealmReborn/Dungeon/D08Qarn/D081Teratotaur.cs, BossMod/Modules/RealmReborn/Dungeon/D08Qarn/D082TempleGuardian.cs, BossMod/Modules/RealmReborn/Dungeon/D08Qarn/D083Adjudicator.cs
Updated The Sunken Temple of Qarn module for 7.2 changes done to the dungeon.
=> Updated Qarn module

BossMod/Modules/Dawntrail/Dungeon/D10Underkeep/D103ValiaPira.cs, BossMod/Modules/RealmReborn/Dungeon/D06Haukke/D061ManorClaviger.cs, BossMod/Modules/RealmReborn/Dungeon/D06Haukke/D062ManorSteward.cs
Fixed the todo in D061 and verified it.
Created new module for D062 Steward/Jester fight.
=> D061 todo fixed and new D062 module

BossMod/Modules/RealmReborn/Dungeon/D01Sastasha/D013DennTheOrcatoothed.cs, BossMod/Modules/RealmReborn/Dungeon/D07Brayflox/D071GreatYellowPelican.cs, BossMod/Modules/RealmReborn/Dungeon/D07Brayflox/D072InfernoDrake.cs, BossMod/Modules/RealmReborn/Dungeon/D07Brayflox/D073Hellbender.cs
-D013 : changed rectangles showing where adds are spawning to outline's instead of full colored rects'
D07 : Added modules for bosses 1, 2, & 3
=> D013 small update D07 added 3 new modules

BossMod/Modules/RealmReborn/Dungeon/D09CuttersCry/D091MyrmidonPrincess.cs, BossMod/Modules/RealmReborn/Dungeon/D09CuttersCry/D092GiantTunnelWorm.cs, BossMod/Modules/RealmReborn/Dungeon/D09CuttersCry/D093Chimera.cs, BossMod/Modules/RealmReborn/Dungeon/D10StoneVigil/D103Isgebind.cs
- Added a quick module for the first boss, released as WIP.
- Adjusted map size to make it a little closer to arena size.
- Added TODO to revisit all bosses after duty support is added for dungeon.
- Added proper timing to touchdown logic.
=> D09CuttersCry - D103Isgebind

BossMod/Modules/RealmReborn/Dungeon/D27SastashaHard/D271Karlabos.cs, BossMod/Modules/RealmReborn/Dungeon/D27SastashaHard/D272CaptainMadison.cs
Initial progress for Sastasha (Hard) D27. First time with the codebase. Feedback welcome.
=> feat(module): D27 Sastasha (Hard)

BossMod/Modules/RealmReborn/Dungeon/D01Sastasha/D011Chopper.cs, BossMod/Modules/RealmReborn/Dungeon/D01Sastasha/D013DennTheOrcatoothed.cs, BossMod/Modules/RealmReborn/Dungeon/D02Deepcroft/D021VoidSoulcounter.cs, BossMod/Modules/RealmReborn/Dungeon/D02Deepcroft/D022GalvanthTheDominator.cs, BossMod/Modules/RealmReborn/Dungeon/D03Copperbell/D031Kottos.cs, BossMod/Modules/RealmReborn/Dungeon/D03Copperbell/D032IchorousIre.cs, BossMod/Modules/RealmReborn/Dungeon/D03Copperbell/D033Gyges.cs, BossMod/Modules/RealmReborn/Dungeon/D05Totorak/D053Graffias.cs, BossMod/Modules/RealmReborn/Dungeon/D07Brayflox/D071GreatYellowPelican.cs, BossMod/Modules/RealmReborn/Dungeon/D07Brayflox/D072InfernoDrake.cs, BossMod/Modules/RealmReborn/Dungeon/D07Brayflox/D073Hellbender.cs, BossMod/Modules/RealmReborn/Dungeon/D08Qarn/D081Teratotaur.cs, BossMod/Modules/RealmReborn/Dungeon/D08Qarn/D083Adjudicator.cs, BossMod/Modules/RealmReborn/Dungeon/D09CuttersCry/D091MyrmidonPrincess.cs, BossMod/Modules/RealmReborn/Dungeon/D10StoneVigil/D101ChudoYudo.cs, BossMod/Modules/RealmReborn/Dungeon/D12AurumVale/D123MisersMistress.cs, BossMod/Modules/RealmReborn/Dungeon/D26Snowcloak/D262Yeti.cs, BossMod/Modules/RealmReborn/Dungeon/D26Snowcloak/D263Fenrir.cs, BossMod/Modules/RealmReborn/Dungeon/D27SastashaHard/D271Karlabos.cs, BossMod/Modules/RealmReborn/Dungeon/D27SastashaHard/D272CaptainMadison.cs, BossMod/Modules/RealmReborn/Dungeon/D29KeeperOfTheLake/D293Midgardsormr.cs
- just some small code cleanup in the RR dungeons in enums.
- added hint to D022 fight to attack imps when boss is invuln'
=> Minor code cleanup, small addition to D022

BossMod/Modules/Stormblood/Trial/T05Yojimbo/DragonNight.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/DragonsLair.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/ElectrogeneticForce2.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/Enchain.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/EpicStormsplitter.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/Fragility.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/Gekko2.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/GigaJump.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/HellsGate.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/Kasha2.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/T05Yojimbo.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/T05YojimboEnums.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/T05YojimboStates.cs
- T05Yojimbo module finished up for Stormblood Kugane Ohashi Trial
=> T05Yojimbo

BossMod/Modules/Dawntrail/Hunt/RankA/TheRaintriller.cs, BossMod/Modules/Endwalker/Trial/T08Asura/T08Asura.cs, BossMod/Modules/Global/MaskedCarnivale/Stage07AChorusSlime/Stage07Act1.cs, BossMod/Modules/Heavensward/Dungeon/D15Xelphatol/D152DotoliCiloc.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/DragonsLair.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/ElectrogeneticForce2.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/Enchain.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/Gekko2.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/HellsGate.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/Kasha2.cs, BossMod/Modules/Stormblood/Trial/T05Yojimbo/T05Yojimbo.cs
- Adjusted some things and removed leftover code in T05Yojimbo
- Small removals of some unused headers in other modules
=> Small code cleanup & adjustments

BossMod/Autorotation/MiscAI/NormalMovement.cs, BossMod/Autorotation/MiscAI/StayCloseToTarget.cs, BossMod/Pathfinding/NavigationDecision.cs
Add condition to allow movement when casts are newly started to prevent movement then cast spam.
=> Fix movement cast spam
